# Generated by Django 5.1.6 on 2025-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_trainers'),
        ('trainers', '0002_alter_trainer_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='trainers_list', to='courses.course'),
        ),
    ]
