# Generated by Django 5.1.6 on 2025-03-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='courses',
            new_name='course',
        ),
    ]
