# Generated by Django 5.1.6 on 2025-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_suitable_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='trainers_photos/')),
                ('courses', models.ManyToManyField(blank=True, related_name='trainers', to='courses.course')),
            ],
        ),
    ]
