# Generated by Django 5.1.6 on 2025-03-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service',
            new_name='course',
        ),
    ]
