# Generated by Django 5.1.6 on 2025-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/detail_images/'),
        ),
    ]
