# Generated by Django 5.1.6 on 2025-03-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_price_course_time_alter_course_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='suitable_for',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Для кого подходит'),
        ),
    ]
