# Generated by Django 5.1.6 on 2025-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_suitable_for'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='courses_set', to='trainers.trainer', verbose_name='Тренеры'),
        ),
    ]
