# Generated by Django 5.1.6 on 2025-12-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Картинка карточки')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='courses/detail_images/', verbose_name='Картинка для детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time', models.CharField(max_length=100, verbose_name='Время')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('suitable_for', models.CharField(blank=True, max_length=200, null=True, verbose_name='Для кого подходит')),
            ],
        ),
    ]
