# Generated by Django 5.1.6 on 2025-12-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='courses_list', to='trainers.trainer'),
        ),
    ]
