# Generated by Django 5.1.6 on 2025-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_trainers'),
        ('trainers', '0002_alter_trainer_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='courses_list', to='trainers.trainer'),
        ),
    ]
