# Generated by Django 5.1.6 on 2025-03-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_service_booking_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='direction',
            field=models.CharField(choices=[('trainer', 'Выбрать тренера'), ('course ', 'Выбрать услугу')], max_length=20, verbose_name='Выбор направления'),
        ),
    ]
