# Generated by Django 5.1.6 on 2025-11-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='direction',
        ),
    ]
